{% set name = "diagrams" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c09311f9a0483fae605d819134c49dac690ec1b8f001300c30916871469cdbac

build:
  number: 0

requirements:
  build:
    - posix  # [win]
  host:
    - pip
    - python
  run:
    - python-graphviz >=0.13.2,<0.14.0
    - jinja2 >=2.10,<3.0
    - python
    - contextvars >=2.4,<3.0  # [py36]

test:
  imports:
    - diagrams
    - diagrams.alibabacloud
    - diagrams.aws
    - diagrams.azure
    - diagrams.base
    - diagrams.custom
    - diagrams.gcp
    - diagrams.k8s
    - diagrams.oci
    - diagrams.onprem

about:
  home: https://diagrams.mingrammer.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diagram as Code
  doc_url: https://diagrams.mingrammer.com/
  dev_url: https://github.com/mingrammer/diagrams

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - dhirschfeld
