{% set name = "diagrams" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 741251174a65e6f4686f96acd37d8f274abcd7aac670526b00ad2891bf39f862

build:
  number: 0
  noarch: python
  script:
    - $PYTHON -m pip install . -vv
    - cp -r $SRC_DIR/resources $SP_DIR/resources
requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python-graphviz >=0.13.2,<0.17.0
    - jinja2 >=2.10,<3.0
    - python >=3.7

test:
  imports:
    - diagrams
    - diagrams.alibabacloud
    - diagrams.aws
    - diagrams.azure
    - diagrams.base
    - diagrams.custom
    - diagrams.gcp
    - diagrams.k8s
    - diagrams.oci
    - diagrams.onprem

about:
  home: https://diagrams.mingrammer.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Diagram as Code
  doc_url: https://diagrams.mingrammer.com/
  dev_url: https://github.com/mingrammer/diagrams

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - dhirschfeld
